FROM requarks/wiki:2
WORKDIR /wiki
ENV DB_TYPE postgres
ENV PGSSLMODE no-verify
ENV DB_HOST $DB_HOST
ENV DB_PORT $DB_PORT
ENV DB_USER $DB_USER
ENV DB_PASS $DB_PASS
ENV DB_NAME $DB_NAME
CMD ["node", "server"]
